name: Build AML Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
    
    - name: Build with NDK
      run: |
        cd jni
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: keylogger-mod
        path: libs/**/*.so
